; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
; Serial Monitor options
monitor_speed = 115200
monitor_flags =
    --encoding
    hexlify

; Optional: Specify upload port if needed
; upload_port = COM3

; Optional: Build flags for specific features
; build_flags = 
;     -DUSE_WIFI
;     -DUSE_BLUETOOTH


